import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.97
padding = {x = 18, y = 16}
dynamic_padding = true
decorations = "Buttonless"
option_as_alt = "Onlyleft"

[font]
normal = {family = "SFMono Nerd Font", style = "Regular"}
size = 19.5
# size = 20.0
bold = { family = "SFMono Nerd Font", style = "Bold" }

